version: 1
build:
  main: cmd/eventchaind
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
- name: observer
  coins:
    - 10000token
    - 100000000stake
  mnemonic:  mesh cage reopen protect marble vendor scheme sleep aspect sweet enrich hill left room embrace waste air general shop blanket genuine person surge hedgehog
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
genesis:
  app_state:
    oracle:
      whitelist: ["cosmos1azge0uza7gxeg5956yxfet3ycyzd59ew5txgp8"] # whitelisting observer on genesis