version: 1
build:
  main: cmd/eventchaind
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
- name: observer1
  coins:
    - 10000token
    - 100000000stake
  mnemonic: minor umbrella weather spin hand addict rabbit vocal sample cargo dash cool soup runway divorce slim mansion divide dinosaur useless glue layer prosper stamp
- name: observer2
  coins:
    - 10000token
    - 100000000stake
  mnemonic: bachelor detail traffic outside copy speak village swing sun mercy genuine meat trim trim cake direct position song garbage bulb gospel fuel loud shield
- name: observer3
  coins:
    - 10000token
    - 100000000stake
  mnemonic: rail hole desk six scheme verify gown material belt idle inform lesson great airport ahead quote vehicle brown juice close ladder sun guide recycle
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
genesis:
  app_state:
    oracle:
      whitelist: ["cosmos1x7hvt2rcc7l3g8wqhk2lxy6cnr987hp4fe7cpx","cosmos1rcppa2x2ffm084jkk5g36npjf45yawe6l6lkjt","cosmos1kzelflkf3yac76sue3v66jty6rn0ylttphaanj"] # whitelisting observer on genesis